apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: camunda-autoscaler-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: camundata-autoscaler-role
subjects:
  - kind: ServiceAccount
    name: camunda-autscaler
    namespace: default